### ISSUE TITLE
cannot reach the project report

### ISSUE THREAD

**Issue by MartinaRuocco** [Bick95/CognitiveRobotics_Robo_Control#1]
Hiya @Bick95 thank you for this repository, it has very clear documentation! 
However, I can't find the report you talk about.. can you please add a hyperlink to your project, please?

**Comment by Bick95** [comment]
Hello @MartinaRuocco, this project started out as a simple final project for a university course. However, later it was decided to take it a bit further, which is happening in the background, but has taken longer already than originally planned given current circumstances. Unfortunately, given the current work in progress, I am afraid that I cannot make the report public yet. I am very sorry about that! As soon as there are any updates on this, I'll update the repo accordingly.

**Comment by MartinaRuocco** [comment]
thank you for your quick response :) I suggest you write these new updates in the readme!
